Update CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,7 @@ jobs:
   build:
     docker:
       # specify the version you desire here
-      - image: circleci/openjdk:8-jdk
+      - image: circleci/android:api-28-alpha
 
     branches:
       only:
@@ -13,6 +13,8 @@ jobs:
 
     environment:
       JAVA_OPTS: -Xmx1536m
+#      GRADLE_USER_HOME: /repo/.gradle
+      TERM: dumb
 
     steps:
       - checkout
@@ -20,32 +22,46 @@ jobs:
           key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
       - restore_cache:
           key: bundle-{{ checksum "Gemfile.lock" }}
+#      - restore_cache:
+#          keys:
+#            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
       - run:
-          name: Bundle install
-          command: bundle install --path vendor/bundle
+          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
+          command: sudo chmod +x ./gradlew
+#      - restore_cache:
+#          keys:
+#            - gradle-cache-{{ checksum "build.gradle" }}
+#            - gradle-cache
+#      - restore_cache:
+#          keys:
+#            - gradle-build-caches-{{ .Revision }}
+#            - gradle-build-caches
+#      - run:
+#          name: Restoring Gradle Build Caches
+#          command: |
+#            [ -d ~/gradle-build-caches ] &&
+#              [ -n "$(ls -A ~/gradle-build-caches)" ] &&
+#              rm -rf ~/.gradle/caches/build-cache-* &&
+#              mv ~/gradle-build-caches/* ~/.gradle/caches/ || true
       - save_cache:
           paths:
-            - vendor/bundle
-          key: bundle-{{ checksum "Gemfile.lock" }}
+            - ~/.gradle
+          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
+#      - save_cache:
+#          paths:
+#            - ~/.gradle/wrapper/
+#          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
+#      - save_cache:
+#          paths:
+#            - ~/.gradle/caches/
+#          key: gradle-cache-{{ checksum "build.gradle" }}
       - run:
           name: Download Dependencies
           command: ./gradlew androidDependencies
-      - save_cache:
-          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
-          paths:
-            - ~/.gradle
-      - run:
-          name: Build
-          command: |
-              if [ $CIRCLE_BRANCH = 'develop' -o $CIRCLE_BRANCH = 'release' ]; then
-                  ./gradlew --offline --stacktrace assembleRelease
-              else
-                  ./gradlew --offline --stacktrace assemble${APP_BUILD_TYPE^}
-              fi
       - run:
           name: Check
           command: |
-              if [ ! $CIRCLE_BRANCH = 'develop' -a ! $CIRCLE_BRANCH = 'release' ]; then
+              if [ ! $CIRCLE_BRANCH = 'develop']; then
                   ./gradlew --stacktrace lint${APP_BUILD_TYPE^}
                   ./gradlew --stacktrace ktlint${APP_BUILD_TYPE^}Check
                   bundle exec danger
